# Generated by Django 3.2.15 on 2022-12-24 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('mother_tongue', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('Future_goals', models.CharField(max_length=100)),
                ('new_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
